export type ResultTier = {
  id: string;
  min: number;
  max: number;
  name: string;
  message: string;
  image: string;
  emoji: string;
  accent: string;
  alt: string;
};

export const campaignConfig = {
  brand: {
    name: "سويتر",
    campaign: "تهمنا",
    hashtag: "#سيارتك_تهمنا",
  },
  colors: {
    orange: "#ff5a1f",
    accent: "#1389ff",
    ink: "#171512",
    cream: "#fff8ea",
  },
  calculator: {
    min: 1,
    max: 240,
    step: 1,
    defaultValue: 67,
  },
  shareUrl: "https://sweater.sa/tahmna",
  bookingUrl: "https://sweater.sa/",
  fallbackDiscount: {
    code: "TAHMNA-DEMO",
    value: "خصم 20٪",
    expiresAt: "31 ديسمبر 2026",
    terms: "على أول حجز عبر سويتر، بحد أقصى 30 ر.س.",
  },
  tiers: [
    {
      id: "meme-tier-1",
      min: 1,
      max: 25,
      name: "الضيف الخفيف",
      message: "سيارتك للحين ما لحقت تحفظ اسمك.",
      image: "/memes/meme-tier-1.webp",
      emoji: "👋",
      accent: "#72d7ff",
      alt: "صورة تعبيرية لشخصية الضيف الخفيف",
    },
    {
      id: "meme-tier-2",
      min: 26,
      max: 40,
      name: "راعي المشاوير الخفيفة",
      message: "مشوارين وترجع… وضعك للحين بالسليم.",
      image: "/memes/meme-tier-2.webp",
      emoji: "😌",
      accent: "#1389ff",
      alt: "صورة تعبيرية لشخصية راعي المشاوير الخفيفة",
    },
    {
      id: "meme-tier-3",
      min: 41,
      max: 45,
      name: "مشوار على السريع",
      message: "تدخل السيارة وتطلع قبل لا تخلص الأغنية.",
      image: "/memes/meme-tier-3.webp",
      emoji: "⚡",
      accent: "#ffb238",
      alt: "صورة تعبيرية لشخصية مشوار على السريع",
    },
    {
      id: "meme-tier-4",
      min: 46,
      max: 50,
      name: "رفيق الإشارة",
      message: "الإشارة تعرفك… بس للحين ما حفظت رقم لوحتك.",
      image: "/memes/meme-tier-4.webp",
      emoji: "🚦",
      accent: "#ff7a50",
      alt: "صورة تعبيرية لشخصية رفيق الإشارة",
    },
    {
      id: "meme-tier-5",
      min: 51,
      max: 55,
      name: "خبير الاختصارات",
      message: "تعرف كل لفة سرية… وتعلق فيها بعد.",
      image: "/memes/meme-tier-5.webp",
      emoji: "🗺️",
      accent: "#b99cff",
      alt: "صورة تعبيرية لشخصية خبير الاختصارات",
    },
    {
      id: "meme-tier-6",
      min: 56,
      max: 60,
      name: "ابن الطريق",
      message: "واضح إن السيارة جزء رسمي من جدولك اليومي.",
      image: "/memes/meme-tier-6.webp",
      emoji: "😎",
      accent: "#ff5a1f",
      alt: "صورة تعبيرية لشخصية ابن الطريق",
    },
    {
      id: "meme-tier-7",
      min: 61,
      max: 70,
      name: "صاحب الخط",
      message: "لو الطريق يتكلم قال: وصل صاحبنا.",
      image: "/memes/meme-tier-7.webp",
      emoji: "🛣️",
      accent: "#72d7ff",
      alt: "صورة تعبيرية لشخصية صاحب الخط",
    },
    {
      id: "meme-tier-8",
      min: 71,
      max: 75,
      name: "مندوب نفسه",
      message: "كل يوم عندك توصيل… حتى لو ما طلب منك أحد.",
      image: "/memes/meme-tier-8.webp",
      emoji: "📦",
      accent: "#1389ff",
      alt: "صورة تعبيرية لشخصية مندوب نفسه",
    },
    {
      id: "meme-tier-9",
      min: 76,
      max: 80,
      name: "موظف السيارة",
      message: "أنت والسيارة بينكم دوام رسمي وعقد غير مكتوب.",
      image: "/memes/meme-tier-9.webp",
      emoji: "🫡",
      accent: "#ffb238",
      alt: "صورة تعبيرية لشخصية موظف السيارة",
    },
    {
      id: "meme-tier-10",
      min: 81,
      max: 85,
      name: "مدير المشاوير",
      message: "جدولك مو مواعيد… جدولك مخارج ودوارات.",
      image: "/memes/meme-tier-10.webp",
      emoji: "📋",
      accent: "#ff7a50",
      alt: "صورة تعبيرية لشخصية مدير المشاوير",
    },
    {
      id: "meme-tier-11",
      min: 86,
      max: 90,
      name: "خبير الزحمة",
      message: "تعرف الزحمة من صوت البوري قبل تشوفها.",
      image: "/memes/meme-tier-11.webp",
      emoji: "🚗",
      accent: "#b99cff",
      alt: "صورة تعبيرية لشخصية خبير الزحمة",
    },
    {
      id: "meme-tier-12",
      min: 91,
      max: 95,
      name: "راعي المسار الطويل",
      message: "المشوار عندك يبدأ بودكاست وينتهي بموسم كامل.",
      image: "/memes/meme-tier-12.webp",
      emoji: "🎧",
      accent: "#ff5a1f",
      alt: "صورة تعبيرية لشخصية راعي المسار الطويل",
    },
    {
      id: "meme-tier-13",
      min: 96,
      max: 100,
      name: "دوام متنقل",
      message: "ناقص تحط بصمة حضور على الدركسون.",
      image: "/memes/meme-tier-13.webp",
      emoji: "💼",
      accent: "#72d7ff",
      alt: "صورة تعبيرية لشخصية دوام متنقل",
    },
    {
      id: "meme-tier-14",
      min: 101,
      max: 130,
      name: "ساكن على الطريق",
      message: "سلامات… تنام في السيارة أنت؟",
      image: "/memes/meme-tier-14.webp",
      emoji: "😴",
      accent: "#1389ff",
      alt: "صورة تعبيرية لشخصية ساكن على الطريق",
    },
    {
      id: "meme-tier-15",
      min: 131,
      max: 160,
      name: "مستأجر السيارة",
      message: "واضح تدفع الإيجار بالبنزين والكيلومترات.",
      image: "/memes/meme-tier-15.webp",
      emoji: "🔑",
      accent: "#ffb238",
      alt: "صورة تعبيرية لشخصية مستأجر السيارة",
    },
    {
      id: "meme-tier-16",
      min: 161,
      max: 190,
      name: "صاحب المجلس المتنقل",
      message: "السيارة عندك مجلس ومكتب وغرفة انتظار.",
      image: "/memes/meme-tier-16.webp",
      emoji: "🛋️",
      accent: "#ff7a50",
      alt: "صورة تعبيرية لشخصية صاحب المجلس المتنقل",
    },
    {
      id: "meme-tier-17",
      min: 191,
      max: 220,
      name: "مالك العقار",
      message: "خلاص، نطلع لك صك على السيارة؟",
      image: "/memes/meme-tier-17.webp",
      emoji: "🏠",
      accent: "#b99cff",
      alt: "صورة تعبيرية لشخصية مالك العقار",
    },
    {
      id: "meme-tier-18",
      min: 221,
      max: 240,
      name: "شيخ الخطوط",
      message: "الطرق كلها تعرفك… باقي يسلمون عليك عند المخرج.",
      image: "/memes/meme-tier-18.webp",
      emoji: "👑",
      accent: "#ff5a1f",
      alt: "صورة تعبيرية لشخصية شيخ الخطوط",
    },
  ] satisfies ResultTier[],
};

export const getTier = (minutes: number) =>
  campaignConfig.tiers.find((tier) => minutes >= tier.min && minutes <= tier.max) ??
  campaignConfig.tiers[campaignConfig.tiers.length - 1];
